# Generated by Django 3.2.3 on 2021-11-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articlecomment_article'),
        ('articles', '0003_auto_20211124_2040'),
    ]

    operations = [
    ]
